### ISSUE TITLE
Kroatien

### ISSUE THREAD

**Issue by julianbernauer** [julianbernauer/polidoc#329]

**Comment by julianbernauer** [comment]
@david-artukovic: Du kannst hier gerne einen Anfang machen

**Comment by david-artukovic** [comment]
- Wahlprogramme aller im Parlament vertretenen Parteien im Zuge der Parlamentswahl 2016 zusammengesucht.

**Comment by david-artukovic** [comment]
- Formatierung in txt und Überarbeitung, sowie upload auf repcong stehen noch aus

**Comment by julianbernauer** [comment]
Sehr gut, die pdfs können gerne schonmal auf repcong

**Comment by david-artukovic** [comment]
Morgen sollten auch die txt-Dateien schon alle fertig sein. Lade dann alles hoch.

Liebe Grüße
David

Gesendet von Mail für Windows 10

Von: Julian Bernauer
Gesendet: Mittwoch, 7. November 2018 13:48
An: julianbernauer/polidoc
Cc: david-artukovic; Mention
Betreff: Re: [julianbernauer/polidoc] Kroatien (#329)

Sehr gut, die pdfs können gerne schonmal auf repcong
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by julianbernauer** [comment]
@david-artukovic 
Hast Du auf repcong schon einen Ordner für Kroatien angelegt?

**Comment by david-artukovic** [comment]
@julianbernauer 
Ja habe ein Ordner erstellt und die PDF's und txt Dateien der Wahlprogramme bzw. Parteiprogramme zu den nationalen Wahlen 2016 hochgeladen.

**Comment by julianbernauer** [comment]
Merci!
